---
title: "4. Overview of algorithms"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

$~$

### Introduction

In this exercise, you will:

- Gain experience working with a variety of different algorithms used for SDMs/ENMs.

**Overview of algorithms**

There is a wide range of different modeling algorithms used for SDMs/ENMs ranging from simple envelope (or 'profile') methods (e.g., BIOCLIM), to GLMs (e.g., logistic regression), machine-learning algorithms (e.g., maxent, Random Forest), and complex methods that can be used to model multiple species at once ('joint SDMs'). 

The Biodiversity and Climate Change Virtual Laboratory has compiled [this useful site](https://support.bccvl.org.au/support/solutions/articles/6000083199-overview-of-sdm-methods-in-bccvl) that provides a detailed description of different model algorithms but does not include R examples.

The 

- Presence-absence
  - GLM

- Presence-only
  - `maxnet`: [R package](https://cran.r-project.org/web/packages/maxnet/maxnet.pdf)
  - `biomod2`: [R package](https://github.com/biomodhub/biomod2)
  - `embarcadero`: [R package](https://github.com/cjcarlson/embarcadero)

- Joint SDMs (multi-species)
    - `hSDM`: [R package](https://ecology.ghislainv.fr/hSDM/)
    - `HMSC`: [Homepage](https://www2.helsinki.fi/en/researchgroups/statistical-ecology/hmsc), [publication](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13345), [Github](https://github.com/hmsc-r/HMSC)

$~$

### 

https://damariszurell.github.io/HU-GCIB/5_SDM_algorithms.html
