---
title: "Additional Resources"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

<!-- $~$ -->

<!-- ## Online tutorials and workshops -->

This course is a very brief introduction to the broad topic of SDMs / ENMs. There are lots of other excellent resources available online, some which are compiled here.

$~$

## Tutorials on SDM/ENMs

- [ENM2020 course (YouTube playlist with lectures)](https://youtube.com/playlist?list=PLhEJuWmv8Jf67qSdifDvgOk5DOJsNNiam) *organized by T. Peterson*
  - [Schedule with PDFs of presentations](https://docs.google.com/spreadsheets/d/1RQu1XRKyYfrnFI2V1g677d0sf8tFxC2xUvb96cbP02s/edit?usp=sharing)
- [Intro to SDM in R](https://damariszurell.github.io/SDM-Intro/) *by D. Zurell*
- [Best Practices in Species Distribution Modeling: A Workshop in R](http://www.earthskysea.org/best-practices-in-species-distribution-modeling-a-workshop-in-r/) *by A. Smith*
- [Species distribution modeling in R](https://rspatial.org/raster/sdm/index.html) *by R. Hijmans and J. Elith*

$~$

## General spatial data analysis in R

- [Spatial Data Science](https://www.rspatial.org/raster/index.html) *by R. Hijmans*
- [Spatial Data Science with applications in R](https://keen-swartz-3146c4.netlify.app/) *by E. Pebesma and R. Bivand*
- [Geocomputation in R](https://geocompr.robinlovelace.net/) *by R. Lovelace, J. Nowosad, J. Muenchow*
- [NEON data science tutorials](https://www.neonscience.org/resources/learning-hub/tutorials)

$~$

## Recommended Reading 

*Work in progress...*

### General
  
- [Merow, C., Smith, M.J., Edwards, T.C., Jr, Guisan, A., McMahon, S.M., Normand, S., et al. (2014). What do we gain from simplicity versus complexity in species distribution models? Ecography , 37, 1267–1281.](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.00845)

$~$

### Best practices

- [Zurell, D., Franklin, J., König, C., Bouchet, P.J., Dormann, C.F., Elith, J., et al. (2020). A standard protocol for reporting species distribution models. Ecography, 43, 1261–1277.](pdfs/Zurell_etal_Ecography_2020.pdf)

- [Araújo, M. B., R. P. Anderson, A. M. Barbosa, C. M. Beale, C. F. Dormann, R. Early, R. A. Garcia, et al. 2019. “Standards for Distribution Models in Biodiversity Assessments.” Science Advances 5: eaat4858.](https://advances.sciencemag.org/content/5/1/eaat4858)

- [Merow, C., Maitner, B.S., Owens, H.L., Kass, J.M., Enquist, B.J. et al. (2019) Species' range model metadata standards: Rmms. Global Ecology and Biogeography, 28, 1912-1924.](https://onlinelibrary.wiley.com/doi/full/10.1111/geb.12993)

$~$

### Incorporating adaptive potential

- [Bush, A., Mokany, K., Catullo, R., Hoffmann, A., Kellermann, V. et al. (2016) Incorporating evolutionary adaptation in species distribution modelling reduces projected vulnerability to climate change. Ecology Letters, 19, 1468-1478.](pdfs/adapt/Bush et al. 2016.pdf)

- [Chardon, N.I., Pironon, S., Peterson, M.L. & Doak, D.F. (2020) Incorporating intraspecific variation into species distribution models improves distribution predictions, but cannot predict species traits for a wide-spread plant species. Ecography, 43, 60-74.](pdfs/adapt/Chardon et al. 2020.pdf)

- [Chen, Q., Yin, Y., Zhao, R., Yang, Y., Teixeira da Silva, J.A. et al. (2020) Incorporating local adaptation into species distribution modeling of paeonia mairei, an endemic plant to china. Frontiers in Plant Science, 10, 1717.](pdfs/adapt/Chen et al. 2020.pdf)

- [Hällfors, M.H., Liao, J., Dzurisin, J., Grundel, R., Hyvärinen, M. et al. (2016) Addressing potential local adaptation in species distribution models: Implications for conservation under climate change. Ecological Applications, 26, 1154-1169.](pdfs/adapt/Hällfors_et_al-2016-Ecological_Applications.pdf)

- [Miller, J.A. & Holloway, P. (2015) Incorporating movement in species distribution models. Progress in Physical Geography: Earth and Environment, 39, 837-849.](pdfs/adapt/Miller & Holloway 2015.pdf)

- [Peterson, M.L., Doak, D.F. & Morris, W.F. (2019) Incorporating local adaptation into forecasts of species’ distribution and abundance under climate change. Global Change Biology, 25, 775-793.](pdfs/adapt/Peterson et al. 2018.pdf)

- [Razgour, O., Forester, B., Taggart, J.B., Bekaert, M., Juste, J. et al. (2019) Considering adaptive genetic variation in climate change vulnerability assessment reduces species range loss projections. Proceedings of the National Academy of Sciences, 116, 10418.](Razgour et al. 2019.pdf)

- [Uden, D.R., Allen, C.R., Angeler, D.G., Corral, L. & Fricke, K.A. (2015) Adaptive invasive species distribution models: A framework for modeling incipient invasions. Biological Invasions, 17, 2831-2850.](Udenart_10 1007_s10530-015-0914-3.pdf)

$~$

### Citizen science data

- [Bradsworth, N., White, J.G., Isaac, B. & Cooke, R. (2017) Species distribution models derived from citizen science data predict the fine scale movements of owls in an urbanizing landscape. Biological Conservation, 213, 27-35.](pdfs/citsci/Bradsworth et al. 2017.pdf)

- [Feldman, M.J., Imbeau, L., Marchand, P., Mazerolle, M.J., Darveau, M. et al. (2021) Trends and gaps in the use of citizen science derived data as input for species distribution models: A quantitative review. PLoS ONE, 16, e0234587.](pdfs/citsci/Feldman et al. 2021.pdf)

- [Fournier, A.M.V., Sullivan, A.R., Bump, J.K., Perkins, M., Shieldcastle, M.C. et al. (2017) Combining citizen science species distribution models and stable isotopes reveals migratory connectivity in the secretive virginia rail. Journal of Applied Ecology, 54, 618-627.](pdfs/citsci/Fournier et al. 2017.pdf)

- [Gaul, W., Sadykova, D., White, H.J., Leon-Sanchez, L., Caplat, P. et al. (2020) Data quantity is more important than its spatial bias for predictive species distribution modelling. PeerJ, 8, e10411.](pdfs/citsci/Gaul et al. 2020.pdf)

- [Matutini, F., Baudry, J., Pain, G., Sineau, M. & Pithon, J. (2021) How citizen science could improve species distribution models and their independent assessment. Ecology and Evolution, 11, 3028-3039.](pdfs/citsci/Matutini et al. 2021.pdf)

- [Milanesi, P., Mori, E. & Menchetti, M. (2020) Observer-oriented approach improves species distribution models from citizen science data. Ecology and Evolution, 10, 12104-12114.](pdfs/citsci/Milanesi et al. 2020.pdf)

- [Steen, V.A., Elphick, C.S. & Tingley, M.W. (2019) An evaluation of stringent filtering to improve species distribution models from citizen science data. Diversity and Distributions, 25, 1857-1869.](pdfs/citsci/Steen et al. 2019.pdf)

$~$

### Model Evaluation

- [Muscarella, R., Galante, P.J., Soley-Guardia, M., Boria, R.A., Kass, J.M., Uriarte, M., et al. (2014). ENMeval: An R package for conducting spatially independent evaluations and estimating optimal model complexity for Maxent ecological niche models. Methods Ecol. Evol., 5, 1198–1205.](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12261)

- [Kass, J.M., Muscarella, R., Galante, P.J., Bohl, C.L., Pinilla‐Buitrago, G.E., Boria, R.A., Soley‐Guardia, M. and Anderson, R.P. (2021), ENMeval 2.0: redesigned for customizable and reproducible modeling of species’ niches and distributions. Methods in Ecology and Evolution.)](https://doi.org/10.1111/2041-210X.13628)

**pROC**

- [Peterson, A. T., Papeş, M., & Soberón, J. (2008). Rethinking receiver operating characteristic analysis applications in ecological niche modeling. Ecological modelling, 213(1), 63-72.](https://www.sciencedirect.com/science/article/pii/S0304380007006163)

**AUC**

- [Lobo, J. M., Jiménez‐Valverde, A., & Real, R. (2008). AUC: a misleading measure of the performance of predictive distribution models. Global ecology and Biogeography, 17(2), 145-151.](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1466-8238.2007.00358.x)

**Continuous Boyce Index**

- [Hirzel, A. H., Le Lay, G., Helfer, V., Randin, C., & Guisan, A. (2006). Evaluating the ability of habitat suitability models to predict species presences. Ecological Modelling, 199(2), 142-152.](https://www.sciencedirect.com/science/article/pii/S0304380006002468)

**AIC for SDMs**

- [Warren, D. L., & Seifert, S. N. (2011). Ecological niche modeling in Maxent: the importance of model complexity and the performance of model selection criteria. Ecological applications, 21(2), 335-342.](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/10-1171.1)

- [Velasco, J. A., & González-Salazar, C. (2019). Akaike information criterion should not be a “test” of geographical prediction accuracy in ecological niche modelling. Ecological Informatics, 51, 25-32.](https://www.sciencedirect.com/science/article/pii/S1574954118302577)

**Leave-one-out CV**

- [Shcheglovitova, M., & Anderson, R. P. (2013). Estimating optimal complexity for ecological niche models: a jackknife approach for species with small sample sizes. Ecological Modelling, 269, 9-17](https://www.sciencedirect.com/science/article/pii/S0304380013004043)

**Spatial blocks**

- [Radosavljevic, A., & Anderson, R. P. (2014). Making better Maxent models of species distributions: complexity, overfitting and evaluation. Journal of Biogeography, 41(4), 629-643.](https://onlinelibrary.wiley.com/doi/full/10.1111/jbi.12227)

**Block partitions in general**

- [Roberts, D. R., Bahn, V., Ciuti, S., Boyce, M. S., Elith, J., Guillera‐Arroita, G., ... & Dormann, C. F. (2017). Cross‐validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure. Ecography, 40(8), 913-929.](https://onlinelibrary.wiley.com/doi/10.1111/ecog.02881)

**blockCV package**

- [Valavi, R., Elith, J., Lahoz‐Monfort, J. J., & Guillera‐Arroita, G. (2019). block CV: An r package for generating spatially or environmentally separated folds for k‐fold cross‐validation of species distribution models. Methods in Ecology and Evolution, 10(2), 225-232.](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13107) and [R package](https://github.com/rvalavi/blockCV)

$~$

### Background selection

- [Barbet-Massin, M., Jiguet, F., Albert, C.H. & Thuiller, W. (2012) Selecting pseudo-absences for species distribution models: How, where and how many? Methods in Ecology and Evolution, 3, 327-338.](https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/j.2041-210X.2011.00172.x)

$~$

### SDMs as biotic variables

- [Kass, J.M., Anderson, R.P., Espinosa-Lucas, A., Juárez-Jaimes, V., Martínez-Salas, E. et al. (2020) Biotic predictors with phenological information improve range estimates for migrating monarch butterflies in mexico. Ecography, 43, 341-352.](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.04886)

- [Palacio, F.X. & Girini, J.M. (2018) Biotic interactions in species distribution models enhance model performance and shed light on natural history of rare birds: A case study using the straight-billed reedhaunter limnoctites rectirostris. Journal of Avian Biology, 49, e01743.](https://onlinelibrary.wiley.com/doi/10.1111/jav.01743)

- [Heikkinen, R.K., Luoto, M., Virkkala, R., Pearson, R.G. & Körber, J.-H. (2007) Biotic interactions improve prediction of boreal bird distributions at macro-scales. Global Ecology and Biogeography, 16, 754-763.](https://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2007.00345.x)

- [Araújo, M.B. & Luoto, M. (2007) The importance of biotic interactions for modelling species distributions under climate change. Global Ecology and Biogeography, 16, 743-753.](https://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2007.00359.x)

- [Bateman, B.L., VanDerWal, J., Williams, S.E. & Johnson, C.N. (2012) Biotic interactions influence the projected distribution of a specialist mammal under climate change. Diversity and Distributions, 18, 861-872.](https://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2012.00922.x)

- [Hof, A.R., Jansson, R. & Nilsson, C. (2012) How biotic interactions may alter future predictions of species distributions: Future threats to the persistence of the arctic fox in fennoscandia. Diversity and Distributions, 18, 554-562.](https://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2011.00876.x)

- [Giannini, T.C., Chapman, D.S., Saraiva, A.M., Alves-dos-Santos, I. & Biesmeijer, J.C. (2013) Improving species distribution models using biotic interactions: A case study of parasites, pollinators and plants. Ecography, 36, 649-656.](https://onlinelibrary.wiley.com/doi/10.1111/j.1600-0587.2012.07191.x)

- [Atauchi, P.J., Peterson, A.T. & Flanagan, J. (2018) Species distribution models for peruvian plantcutter improve with consideration of biotic interactions. Journal of Avian Biology, 49, jav-01617.](https://onlinelibrary.wiley.com/doi/10.1111/jav.01617)

- [Wisz, M.S., Pottier, J., Kissling, W.D., Pellissier, L., Lenoir, J. et al. (2013) The role of biotic interactions in shaping distributions and realised assemblages of species: Implications for species distribution modelling. Biological Reviews, 88, 15-30.](https://onlinelibrary.wiley.com/doi/10.1111/j.1469-185X.2012.00235.x)

- [Belmaker, J., Zarnetske, P., Tuanmu, M.-N., Zonneveld, S., Record, S. et al. (2015) Empirical evidence for the scale dependence of biotic interactions. Global Ecology and Biogeography, 24, 750-761.](https://onlinelibrary.wiley.com/doi/10.1111/geb.12311)

$~$

### Virtual species / simulation

- [Meynard, C.N., Leroy, B. & Kaplan, D.M. (2019) Testing methods in species distribution modelling using virtual species: What have we learnt and what are we missing? Ecography, 42, 2021-2036.](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.04385)

- [Inman, R., Franklin, J., Esque, T. & Nussear, K. (2021) Comparing sample bias correction methods for species distribution modeling using virtual species. Ecosphere, 12, e03422.](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.3422)

- [Santini, L., Benítez-López, A., Maiorano, L., Čengić, M. & Huijbregts, M.A.J. (2021) Assessing the reliability of species distribution projections in climate change research. Diversity and Distributions, 27, 1035-1050.](https://onlinelibrary.wiley.com/doi/10.1111/ddi.13252)

- [Grimmett, L., Whitsed, R. & Horta, A. (2021) Creating virtual species to test species distribution models: The importance of landscape structure, dispersal and population processes. Ecography, 44, 753-765.](https://onlinelibrary.wiley.com/doi/10.1111/ecog.05555)

- [Smith, A.B. & Santos, M.J. (2020) Testing the ability of species distribution models to infer variable importance. Ecography, 43, 1801-1813.](https://onlinelibrary.wiley.com/doi/10.1111/ecog.05317)

- [Leroy, B., Meynard, C.N., Bellard, C. & Courchamp, F. (2016) Virtualspecies, an r package to generate virtual species distributions. Ecography, 39, 599-607.](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.01388)

$~$

### Integrating dispersal

- [Nobis, M.P. & Normand, S. (2014) Kissmig – a simple model for r to account for limited migration in analyses of species distributions. Ecography, 37, 1282-1287.](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.00930)

$~$

### Occurrence data cleaning

- [Arlé, E., Zizka, A., Keil, P., Winter, M., Essl, F., Knight, T., Weigelt, P., Jiménez‐Muñoz, M. and Meyer, C. (2021), bRacatus: a method to estimate the accuracy and biogeographical status of georeferenced biological data. Methods in Ecology and Evolution.](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13629)

- [Zizka, A., Silvestro, D., Andermann, T., Azevedo, J., Duarte Ritter, C. et al. (2019) Coordinatecleaner: Standardized cleaning of occurrence records from biological collection databases. Methods in Ecology and Evolution, 10, 744-751.](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13152)

$~$

### Modeling algorithms

- [Merow, C., Smith, M. & Silander, J.A. (2013). A practical guide to Maxent: what it does, and why inputs and settings matter. Ecography , 36, 1–12.](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1600-0587.2013.07872.x)


