---
title: "Introduction to SDMs: theory and practice in R"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

Bob Muscarella  

$~$

### Introduction
This course was initially developed as a 3-day workshop at Sapienza University in June, 2021. Students have various options to work through at their own pace, following different specific lessons based on their prior knowledge and goals.

**Learning objectives**: In general, by the end of this course, you will be able to:

- Know the basic theory and concepts behind SDMs / ENMs
- Design, build and evaluate SDMs / ENMs using automated R scripts
- Understand the strengths and limitations of SDMs / ENMs for different purposes
- Use SDMs / ENMs to describe, predict, and project species distributions in space and time

$~$

### Before the course

**Reading**

Please read these papers before the course begins as they provide important background information.  We will discuss them on Day 1 of the course.

- [Elith, J., & Leathwick, J. R. (2009). Species distribution models: ecological explanation and prediction across space and time. Annual Review of Ecology, Evolution, and Systematics 40, 677-697.](pdfs/Elith and Leathwick 2009.pdf)
- [Elith, J., & Graham, C. H. (2009) Do they? How do they? WHY do they differ? On finding reasons for differing performances of species distribution models. Ecography 32(1), 66-77.](pdfs/Elith and Graham 2009.pdf)
- [Merow et al. (2014) What do we gain from simplicity versus complexity in species distribution models? Ecography, 37, 1267–1281.](pdfs/Merow et al. 2014.pdf)


**R Exercises**

To prepare for the course, we will use some tutorials produced by the excellent Data Carpentry organization. Follow through the exercises below to refresh your general R skills and get you started with geospatial data and analyses. You are free to skip around in these materials based on your prior knowledge but I encourage you to follow through everything.

1. [Data Carpentry: Introduction to R and RStudio](https://datacarpentry.org/r-intro-geospatial/01-rstudio-intro/index.html)
2. [Data Carpentry: Introduction to Geospatial Concepts](https://datacarpentry.org/organization-geospatial/)
3. ***Optional:*** [Introduction to Geospatial Raster and Vector Data with R](https://datacarpentry.org/r-raster-vector-geospatial/). To complete this exercise, you will first need to [follow the setup instructions](https://datacarpentry.org/geospatial-workshop/setup.html).

*Note: If you are very new to R and want a more detailed introduction, I recommend:* [Data Carpentry: Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/index.html). *Note that going through this entire exercise will take about one full day.*

$~$

### **Day 1**: Introduction: data acquisition and cleaning

**Morning session** (*Theory*)

- [Overview and introductions](lectures/0. Overview and introduction.pdf)
- [Lecture 1: The what, how, why of SDMs/ENMs](lectures/1. The what how why of SDMs ENMs.pdf)
- Discussion of pre-course readings
  - *What did you find most interesting / confusing?*
  - *What seems to be the most challenging aspect of building species distribution model?*

**Afternoon session** (*Practical*)

Obtaining and cleaning data

- [Exercise 1: Species data](Exercise1.html)
- [Exercise 2: Environment data](Exercise2.html)

$~$

### **Day 2**: Models: algorithms and evaluations

**Morning session** (*Theory*)

- [Lecture 2: Model Evaluation](lectures/2. Kass_mod_eval_sapienzaU_2021.pdf) (guest lecture by [Jamie Kass](https://scholar.google.com/citations?user=LM_UNdkAAAAJ&hl=en)). Video recording [here](https://youtu.be/GzF57egpIgQ)

**Afternoon session** (*Practical*)

- Discussion of background (psuedo-absence) point selection. Video recording [here](https://youtu.be/M4UlF2xKaBs)
- [Exercise 3: Overview of algorithms](Exercise3.html)
- [Exercise 4: Model evaluation](Exercise4.html)

$~$

### **Day 3**: Applications: possibilities and precautions

**Morning session** (*Theory*)

- [Lecture 3: Applications: Potentials and pitfalls](lectures/3. Potentials and pitfalls.pdf). Video recording [here](https://youtu.be/rw6fR_Nj0Ws)

**Afternoon session** (*Practical*)

- Live walk-through ENMeval vignette: Video recording [here](https://youtu.be/HH3FenCqBMA)
- Continue exercises, apply knowledge to individual projects

